- name: prometheus.rules
  rules:
    - alert: PushGatewayDown
      expr: sum(min_over_time(up{job="prometheus-pushgateway"}[2m])) by (job,instance) == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."
        summary: "Job {{ $labels.job }} having an issue on {{ $labels.instance }}"
    - alert: PrometheusTSDBWALCorruptions
      expr: tsdb_wal_corruptions_total > 0
      for: 4h
      labels:
        severity: warning
      annotations:
        description: "{{$labels.job}} at {{$labels.instance}} has a corrupted write-ahead log (WAL)."
        summary: "Prometheus write-ahead log is corrupted"
    - alert: PrometheusConfigReloadFailed
      expr: prometheus_config_last_reload_successful == 0
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: reload of Prometheus configuration has failed for {{$labels.instance}}
    - alert: PrometheusErrorSendingAlerts
      expr: rate(prometheus_notifications_errors_total[5m]) / rate(prometheus_notifications_sent_total[5m]) > 0.03
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Errors while sending alerts from Prometheus {{$labels.instance}} to Alertmanager {{$labels.Alertmanager}}"
    - alert: PrometheusTSDBReloadsFailing
      expr: increase(prometheus_tsdb_reloads_failures_total[2h]) > 0
      for: 12h
      labels:
        severity: warning
      annotations:
        description: "{{$labels.job}} at {{$labels.instance}} had {{$value | humanize}} reload failures over the last four hours."
        summary: "Prometheus has issues reloading data blocks from disk"
    - alert: PrometheusJobMissing
      expr: absent(up{job="prometheus"})
      labels:
        severity: warning
      annotations:
        summary: "Prometheus job missing (instance {{ $labels.instance }})"
        description: "A Prometheus job has disappeared"
    - alert: PrometheusTooManyRestarts
      expr: changes(process_start_time_seconds{job=~"prometheus|pushgateway|alertmanager"}[15m]) > 2
      labels:
        severity: warning
      annotations:
        summary: "Prometheus too many restarts (instance {{ $labels.instance }})"
        description: "Prometheus has restarted more than twice in the last 15 minutes. It might be crashlooping."
    - alert: PrometheusAlertmanagerConfigurationReloadFailure
      expr: alertmanager_config_last_reload_successful != 1
      labels:
        severity: warning
      annotations:
        summary: "Prometheus AlertManager configuration reload failure (instance {{ $labels.instance }})"
        description: "AlertManager configuration reload error"
    - alert: PrometheusAlertmanagerConfigNotSynced
      expr: count(count_values("config_hash", alertmanager_config_hash)) > 1
      labels:
        severity: warning
      annotations:
        summary: "Prometheus AlertManager config not synced (instance {{ $labels.instance }})"
        description: "Configurations of AlertManager cluster instances are out of sync"
    - alert: PrometheusNotConnectedToAlertmanager
      expr: prometheus_notifications_alertmanagers_discovered < 1
      labels:
        severity: critical
      annotations:
        summary: "Prometheus not connected to alertmanager (instance {{ $labels.instance }})"
        description: "Prometheus cannot connect the alertmanager"
    - alert: PrometheusRuleEvaluationFailures
      expr: increase(prometheus_rule_evaluation_failures_total[3m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus rule evaluation failures (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} rule evaluation failures, leading to potentially ignored alerts."
    - alert: PrometheusTemplateTextExpansionFailures
      expr: increase(prometheus_template_text_expansion_failures_total[3m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus template text expansion failures (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} template text expansion failures"
    - alert: PrometheusRuleEvaluationSlow
      expr: prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Prometheus rule evaluation slow (instance {{ $labels.instance }})"
        description: "Prometheus rule evaluation took more time than the scheduled interval. It indicates a slower storage backend access or too complex query."
    - alert: PrometheusNotificationsBacklog
      expr: min_over_time(prometheus_notifications_queue_length[10m]) > 0
      labels:
        severity: warning
      annotations:
        summary: "Prometheus notifications backlog (instance {{ $labels.instance }})"
        description: "The Prometheus notification queue has not been empty for 10 minutes"
    - alert: PrometheusAlertmanagerNotificationFailing
      expr: rate(alertmanager_notifications_failed_total[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus AlertManager notification failing (instance {{ $labels.instance }})"
        description: "Alertmanager is failing sending notifications"
    - alert: PrometheusTargetEmpty
      expr: prometheus_sd_discovered_targets == 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus target empty (instance {{ $labels.instance }})"
        description: "Prometheus has no target in service discovery"
    - alert: PrometheusTargetScrapingSlow
      expr: prometheus_target_interval_length_seconds{quantile="0.9"} / on (interval, instance, job) prometheus_target_interval_length_seconds{quantile="0.5"} > 1.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Prometheus target scraping slow (instance {{ $labels.instance }})"
        description: "Prometheus is scraping exporters slowly since it exceeded the requested interval time. Your Prometheus server is under-provisioned."
    - alert: PrometheusLargeScrape
      expr: increase(prometheus_target_scrapes_exceeded_sample_limit_total[10m]) > 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Prometheus large scrape (instance {{ $labels.instance }})"
        description: "Prometheus has many scrapes that exceed the sample limit"
    - alert: PrometheusTargetScrapeDuplicate
      expr: increase(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m]) > 0
      labels:
        severity: warning
      annotations:
        summary: "Prometheus target scrape duplicate (instance {{ $labels.instance }})"
        description: "Prometheus has many samples rejected due to duplicate timestamps but different values"
    - alert: PrometheusTsdbCheckpointCreationFailures
      expr: increase(prometheus_tsdb_checkpoint_creations_failed_total[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus TSDB checkpoint creation failures (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} checkpoint creation failures"
    - alert: PrometheusTsdbCheckpointDeletionFailures
      expr: increase(prometheus_tsdb_checkpoint_deletions_failed_total[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus TSDB checkpoint deletion failures (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} checkpoint deletion failures"
    - alert: PrometheusTsdbCompactionsFailed
      expr: increase(prometheus_tsdb_compactions_failed_total[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus TSDB compactions failed (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} TSDB compactions failures"
    - alert: PrometheusTsdbHeadTruncationsFailed
      expr: increase(prometheus_tsdb_head_truncations_failed_total[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus TSDB head truncations failed (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} TSDB head truncation failures"
    - alert: PrometheusTsdbReloadFailures
      expr: increase(prometheus_tsdb_reloads_failures_total[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus TSDB reload failures (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} TSDB reload failures"
    - alert: PrometheusTsdbWalCorruptions
      expr: increase(prometheus_tsdb_wal_corruptions_total[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus TSDB WAL corruptions (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} TSDB WAL corruptions"
    - alert: PrometheusTsdbWalTruncationsFailed
      expr: increase(prometheus_tsdb_wal_truncations_failed_total[1m]) > 0
      labels:
        severity: critical
      annotations:
        summary: "Prometheus TSDB WAL truncations failed (instance {{ $labels.instance }})"
        description: "Prometheus encountered {{ $value }} TSDB WAL truncation failures"

